language: php

notifications:
  email:
    on_success: never
    on_failure: change
  slack:
    rooms:
      - wsu-ucomm:n2TLZRJd84rMOMbkKthSEMgS
    on_success: change
    on_failure: always
    on_start: never

branches:
  only:
    - master

matrix:
  include:
    - php: 7.0
      env: WP_TRAVISCI=phpcs

before_script:
  - nvm install stable
  - npm install -g grunt-cli
  - npm install
  - npm --version
  - node --version
  - composer install

script:
  - grunt
  - grunt phpcs
